### ISSUE TITLE
Submitting data doesn't appear to save

### ISSUE THREAD

**Issue by jeholliday** [mortorqrobotics/MorScout#3]
In pit scouting mode I entered data for a team and clicked submit.  I then clicked on view and no data was shown.  There also didn't appear to be a data entry created in data.json.

**Comment by Farbod909** [comment]
Fixed

**Comment by jeholliday** [comment]
I tested again with the newest version, and it still doesn't work for me.  Does it work for you?

**Comment by Farbod909** [comment]
It works for me. In detail, can you explain the steps you are taking and what the problem is? Thank you
